version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./flask_app:/app
    environment:
      FLASK_ENV: development
      MYSQL_HOST: mysql-container
      MYSQL_USER: bookwise_flask
      MYSQL_PASSWORD: bookwiseflaskpasswordchangelater
      MYSQL_DB: bookwisetesting
    depends_on:
      mysql-container:
        condition: service_healthy

  mysql-container:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: kMcFNgtzJTA0{XW
      MYSQL_DATABASE: bookwisetesting
      MYSQL_USER: bookwise_flask
      MYSQL_PASSWORD: bookwiseflaskpasswordchangelater
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data: